### PR TITLE
Fix eu s3 name, change default artifact visiblity to private

### PR DESCRIPTION
**Pull request by stephankoelle**

### CODE REVIEW

**Comment by nebhale** [comment]
I'm not going to change the default from the public, as that's a pretty large breaking change, but I'll add a configuration parameter to adjust the visibility.  I'm heading out on holiday, shortly so it may take a little bit to get this in, but rest assured, I'll get it done.

**Comment by nebhale** [comment]
Also, according to [this AWS documentation](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region), the EU location constraint is actually correct.  I'm open to contradicting proof if you've got it though.

**Comment by stephankoelle** [comment]
This must be an error in amazon documentation.
'EU' through an exception, after my fix, it worked.

**Comment by alza-bitz** [comment]
Hi, I am getting the same error (with version 4.7.0.RELEASE):

'eu-west-1' is not a valid location constraint

Please can the change with the correct location constraint be pulled in?

Many Thanks

**Comment by nebhale** [comment]
I'll have a look at this, this evening.

**Comment by nebhale** [comment]
OK, so this is really weird.  @alzadude or @stephankoelle do you have a publicly accessible bucket that is causing this issue for you?  I've got a bucket in Ireland and when I request its location constraint it comes back as `EU`.  I'd like to be able to reproduce the problem before making a correction.

screen shot 2013-05-01 at 16 25 31

**Comment by alza-bitz** [comment]
Hi there,

I have created a new bucket in the 'Ireland' region named 'nineworthies-aws-maven-tests'; I have assigned a bucket policy that allows all s3 actions to any user.

I knocked up a Groovy script to check the bucket location:

``` groovy
@Grapes([
    @Grab(group="com.amazonaws", module="aws-java-sdk", version="1.3.32"),
    @Grab(group="log4j", module="log4j", version="1.2.16")
  ])

import com.amazonaws.auth.*
import com.amazonaws.services.s3.*
import com.amazonaws.services.s3.model.*

def bucketName = "nineworthies-aws-maven-tests"
def s3client = new AmazonS3Client(new AWSCredentialsProviderChain(new EnvironmentVariableCredentialsProvider()))

println "Bucket location for '$bucketName' is '${s3client.getBucketLocation(bucketName)}'"
```

When I execute this script I get the following output:

`Bucket location for 'nineworthies-aws-maven-tests' is 'eu-west-1'`

Btw I noticed in the javadoc for com.amazonaws.services.s3.AmazonS3.getBucketLocation(..), it states "To view the location constraint of a bucket, the user must be the bucket owner."

So, even if you were to run this script with your credentials against my bucket, I'm not sure you would be able to query the location?

Thanks

Alex

**Comment by nebhale** [comment]
In practice the Javadoc is slightly incorrect.  As long as the bucket permissions are are `WORLD_READ`, it'll work.  But I've managed to reproduce the problem using different tools.  Take a look at the commit message for 8437d97 for details.  I'm going to try and get the changes around permissions integrated this morning, but if I can't I'll do a release with just this change in it.

**Comment by alza-bitz** [comment]
Thanks; regarding the permissions changes, I was considering creating a new issue just for those, to keep things separate (btw the hard-coded setting to public read doesn't fit my requirements unfortunately). For a simple solution, I was thinking of an approach where the wagon doesn't actually set any acls, and instead it is the responsibility of the bucket owner to configure a bucket-wide acl or policy to suit their requirements. For example, I have two repos on s3, one is intended to be 'public' (public read) and one 'private' (authenticated read).

However, if you did still want to make the permissions behavior of the wagon configurable, how would you intend to do that? Btw, I am using this wagon for Gradle projects as well as Maven projects.

Thanks

**Comment by nebhale** [comment]
Yeah, I was going to put together a new issue once I started on the work.  It turns out that the [`settings.xml`](http://maven.apache.org/ref/3.0.5/maven-settings/settings.html) file can take configuration that I'm pretty sure is passed to the `Wagon`.  I just need to figure out how this works and this would be my preferred solution.  Would you be looking for a totally custom permissions solution or simply something with canned ACLs?

**Comment by alza-bitz** [comment]
Hi there, personally I think a sensible approach would be for the default case to not set any acl; but, if the user wants they can configure a canned acl to use. Then, the default case will work in environments where a bucket-wide policy or bucket-wide acl is being used (I'm slightly biased, this is my environment :)

As an aside, I'm fairly new to Gradle so I'm not sure how I would be able to configure the wagon for my Gradle projects if I had to anyway. What I have setup for Gradle with this wagon is based on this doc: http://www.gradle.org/docs/current/userguide/maven_plugin.html (50.6.2. 'Deploying to a Maven repository')

**Comment by nebhale** [comment]
I'm closing this issue out as the `eu-west-1` update is complete.  The default permissions changes are going to be tracked in issue #8.

**Comment by alza-bitz** [comment]
Interestingly, if I downgrade to 4.4.0.RELEASE, I don't get the location constraint error, and the upload seems to work (4.5.0 doesn't appear to be available, and 4.6.0 gives the same error as 4.7.0); this will serve as a workaround (at least for me) until a version with the fix is released.

**Comment by nebhale** [comment]
The EU name has been fixed in [`4.8.0.RELEASE`](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.springframework.build%22%20AND%20a%3A%22aws-maven%22) and is now available from Maven Central.  The permissions changes are still forthcoming.

**Pull request closed without merging**
