### PR TITLE
Use password instead of passphrase to store the AWS secret key

### PR DESCRIPTION
**Pull request by jmena**
I'm using maven 3, I don't know why the passphrase is not being sent to the plugin, so, why not using the password? here's my patch

### CODE REVIEW

**Comment by brihgt** [comment]
Thanks!
I spent lots of time to debug the issue.

**Comment by joebalancio** [comment]
+1

This fixes an issue I'm experiencing using the Maven Versions plugin to update dependencies in S3. The quick fix of putting an empty <privateKey/> in settings.xml doesn't play well with the Versions plugin. Using password instead of passphrase fixes this. Thanks!

**Comment by fhanik** [comment]
I am seconding this PR, as I'm experiencing an "Access denied" from S3, but when I pull in this PR, it works great.

**Comment by joebalancio** [comment]
@nebhale Is it possible to prioritize this? Thanks!

**Comment by oravecz** [comment]
Please update and push new version to Maven Central. Pretty useless as it stands.

**Comment by arussel** [comment]
+1

**Comment by ghost** [comment]
+1 This really fixes it!

**Comment by uthark** [comment]
I found workaround for it: just add EMPTY privateKey:

```
<server>
    <id>maven-s3-release-repo</id>
    <username>API KEY</username>
    <privateKey></privateKey>
    <passphrase>SECRET KEY</passphrase>
</server>
```

This works for me on 3.1.1

**Comment by nebhale** [comment]
Complete in the latest snapshot.  I'll get a `5.0.0.RELEASE` out shortly.

**Pull request closed without merging**
